// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: artist_swipe.
// - Entity ID: 102019abe83be8a7336bfbd757bf8ca6d59.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ArtistSwipeDirection
 */
export enum ArtistSwipeDirection {
  Unspecified = 0,
  Like = 1,
  Pass = 2,
}



/**
 * Interface for ArtistSwipeModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ArtistSwipeModel {
  id: string;
  buyer_id: string;
  artist_id: string;
  direction: ArtistSwipeDirection;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for ArtistSwipe entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ArtistSwipeORM {
  private static instance: ArtistSwipeORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be8a7336bfbd757bf8ca6d59';
    this.entityName = 'artist_swipe';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of ArtistSwipeORM
   */
  public static getInstance(): ArtistSwipeORM {
    if (!ArtistSwipeORM.instance) {
      ArtistSwipeORM.instance = new ArtistSwipeORM();
    }
    
    return ArtistSwipeORM.instance;
  }

  /**
   * Get all ArtistSwipe records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllArtistSwipe(): Promise<ArtistSwipeModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ArtistSwipe record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertArtistSwipe(data: ArtistSwipeModel[]): Promise<ArtistSwipeModel[]> {
    const structured = data.map((item) => CreateData(ArtistSwipeModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ArtistSwipe records
   */
  async purgeAllArtistSwipe(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ArtistSwipe records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listArtistSwipe(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ArtistSwipeModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get artist_swipe by Id index
   * This function gets data by index.
   */
  async getArtistSwipeById(
    id: string,
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_swipe by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistSwipeById(
    id: string,
    data: ArtistSwipeModel
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexId(
      id
    );

    const values = ArtistSwipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_swipe by Id index
   */
  async deleteArtistSwipeById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_swipe by ArtistIdBuyerId index
   * This function gets data by index.
   */
  async getArtistSwipeByArtistIdBuyerId(
    artist_id: string,
    buyer_id: string,
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexArtistIdBuyerId(
      artist_id,
      buyer_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_swipe by ArtistIdBuyerId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistSwipeByArtistIdBuyerId(
    artist_id: string,
    buyer_id: string,
    data: ArtistSwipeModel
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexArtistIdBuyerId(
      artist_id,
      buyer_id
    );

    const values = ArtistSwipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_swipe by ArtistIdBuyerId index
   */
  async deleteArtistSwipeByArtistIdBuyerId(
    artist_id: string,
    buyer_id: string
  ): Promise<void> {
    const index = createIndexArtistIdBuyerId(
      artist_id,
      buyer_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_swipe by ArtistIdDirection index
   * This function gets data by index.
   */
  async getArtistSwipeByArtistIdDirection(
    artist_id: string,
    direction: ArtistSwipeDirection,
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexArtistIdDirection(
      artist_id,
      direction
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_swipe by ArtistIdDirection index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistSwipeByArtistIdDirection(
    artist_id: string,
    direction: ArtistSwipeDirection,
    data: ArtistSwipeModel
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexArtistIdDirection(
      artist_id,
      direction
    );

    const values = ArtistSwipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_swipe by ArtistIdDirection index
   */
  async deleteArtistSwipeByArtistIdDirection(
    artist_id: string,
    direction: ArtistSwipeDirection
  ): Promise<void> {
    const index = createIndexArtistIdDirection(
      artist_id,
      direction
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_swipe by DataCreator index
   * This function gets data by index.
   */
  async getArtistSwipeByDataCreator(
    data_creator: string,
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_swipe by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistSwipeByDataCreator(
    data_creator: string,
    data: ArtistSwipeModel
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ArtistSwipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_swipe by DataCreator index
   */
  async deleteArtistSwipeByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_swipe by DataUpdater index
   * This function gets data by index.
   */
  async getArtistSwipeByDataUpdater(
    data_updater: string,
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_swipe by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistSwipeByDataUpdater(
    data_updater: string,
    data: ArtistSwipeModel
  ): Promise<ArtistSwipeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ArtistSwipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_swipe by DataUpdater index
   */
  async deleteArtistSwipeByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ArtistSwipeModel data array
   */
  private resultToData(values: Data[]): ArtistSwipeModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ArtistSwipeModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ArtistSwipeModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ArtistSwipeModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ArtistSwipeModel => item !== null);
  }
}

/**
 * Convert ArtistSwipeModel data to Value array
 */
function ArtistSwipeModelToValues(data: ArtistSwipeModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'buyer_id', type: DataType.string, defaultValue: '' },
    { key: 'artist_id', type: DataType.string, defaultValue: '' },
    { key: 'direction', type: DataType.enumeration, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ArtistSwipeModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ArtistSwipeModel data
 */
function ArtistSwipeModelFromValues(values: Value[]): ArtistSwipeModel {
  const data: Partial<ArtistSwipeModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'buyer_id':
        data.buyer_id = ParseValue(value, DataType.string) as string;
        break;
      case 'artist_id':
        data.artist_id = ParseValue(value, DataType.string) as string;
        break;
      case 'direction':
        data.direction = ParseValue(value, DataType.enumeration) as ArtistSwipeDirection;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ArtistSwipeModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ArtistIdBuyerId fields
 */
function createIndexArtistIdBuyerId(
  artist_id: string,
  buyer_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, artist_id, 'artist_id'),
    CreateValue(DataType.string, buyer_id, 'buyer_id'),
  ];

  return {
    fields: ['artist_id', 'buyer_id'],
    values
  };
}
/**
 * Create index for ArtistIdDirection fields
 */
function createIndexArtistIdDirection(
  artist_id: string,
  direction: ArtistSwipeDirection
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, artist_id, 'artist_id'),
    CreateValue(DataType.enumeration, direction, 'direction'),
  ];

  return {
    fields: ['artist_id', 'direction'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ArtistSwipeORM;