// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: conversation.
// - Entity ID: 102019abe83be89784aa2011e626389d200.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ConversationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ConversationModel {
  id: string;
  participant_ids: string[];
  last_message_time: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Conversation entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ConversationORM {
  private static instance: ConversationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be89784aa2011e626389d200';
    this.entityName = 'conversation';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of ConversationORM
   */
  public static getInstance(): ConversationORM {
    if (!ConversationORM.instance) {
      ConversationORM.instance = new ConversationORM();
    }
    
    return ConversationORM.instance;
  }

  /**
   * Get all Conversation records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllConversation(): Promise<ConversationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Conversation record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertConversation(data: ConversationModel[]): Promise<ConversationModel[]> {
    const structured = data.map((item) => CreateData(ConversationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Conversation records
   */
  async purgeAllConversation(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Conversation records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listConversation(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ConversationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get conversation by Id index
   * This function gets data by index.
   */
  async getConversationById(
    id: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationById(
    id: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexId(
      id
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by Id index
   */
  async deleteConversationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by ParticipantIds index
   * This function gets data by index.
   */
  async getConversationByParticipantIds(
    participant_ids: string[],
  ): Promise<ConversationModel[]> {
    const index = createIndexParticipantIds(
      participant_ids
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by ParticipantIds index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByParticipantIds(
    participant_ids: string[],
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexParticipantIds(
      participant_ids
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by ParticipantIds index
   */
  async deleteConversationByParticipantIds(
    participant_ids: string[]
  ): Promise<void> {
    const index = createIndexParticipantIds(
      participant_ids
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by LastMessageTime index
   * This function gets data by index.
   */
  async getConversationByLastMessageTime(
    last_message_time: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexLastMessageTime(
      last_message_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by LastMessageTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByLastMessageTime(
    last_message_time: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexLastMessageTime(
      last_message_time
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by LastMessageTime index
   */
  async deleteConversationByLastMessageTime(
    last_message_time: string
  ): Promise<void> {
    const index = createIndexLastMessageTime(
      last_message_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by DataCreator index
   * This function gets data by index.
   */
  async getConversationByDataCreator(
    data_creator: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByDataCreator(
    data_creator: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by DataCreator index
   */
  async deleteConversationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by DataUpdater index
   * This function gets data by index.
   */
  async getConversationByDataUpdater(
    data_updater: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByDataUpdater(
    data_updater: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by DataUpdater index
   */
  async deleteConversationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ConversationModel data array
   */
  private resultToData(values: Data[]): ConversationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ConversationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ConversationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ConversationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ConversationModel => item !== null);
  }
}

/**
 * Convert ConversationModel data to Value array
 */
function ConversationModelToValues(data: ConversationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'participant_ids', type: DataType.array, defaultValue: [] },
    { key: 'last_message_time', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ConversationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ConversationModel data
 */
function ConversationModelFromValues(values: Value[]): ConversationModel {
  const data: Partial<ConversationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'participant_ids':
        data.participant_ids = ParseValue(value, DataType.array) as string[];
        break;
      case 'last_message_time':
        data.last_message_time = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ConversationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ParticipantIds fields
 */
function createIndexParticipantIds(
  participant_ids: string[]
): Index {
  const values: Value[] = [
    CreateValue(DataType.array, participant_ids, 'participant_ids'),
  ];

  return {
    fields: ['participant_ids'],
    values
  };
}
/**
 * Create index for LastMessageTime fields
 */
function createIndexLastMessageTime(
  last_message_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, last_message_time, 'last_message_time'),
  ];

  return {
    fields: ['last_message_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ConversationORM;