// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: artist_profile.
// - Entity ID: 102019abe83be8a752ca99d0a431c094db8.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";









/**
 * Interface for ArtistProfileSocialLinksModel
 */
export interface ArtistProfileSocialLinksModel {
  twitter?: string | null;
  instagram?: string | null;
}

/**
 * Interface for ArtistProfileModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ArtistProfileModel {
  id: string;
  user_id: string;
  banner_image_url?: string | null;
  bio?: string | null;
  art_style_tags?: string[] | null;
  portfolio_image_urls?: string[] | null;
  commission_guidelines?: string | null;
  completed_work_count: number;
  likes_count: number;
  price_range_min: number;
  price_range_max: number;
  social_links?: ArtistProfileSocialLinksModel | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for ArtistProfile entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ArtistProfileORM {
  private static instance: ArtistProfileORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be8a752ca99d0a431c094db8';
    this.entityName = 'artist_profile';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of ArtistProfileORM
   */
  public static getInstance(): ArtistProfileORM {
    if (!ArtistProfileORM.instance) {
      ArtistProfileORM.instance = new ArtistProfileORM();
    }
    
    return ArtistProfileORM.instance;
  }

  /**
   * Get all ArtistProfile records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllArtistProfile(): Promise<ArtistProfileModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ArtistProfile record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertArtistProfile(data: ArtistProfileModel[]): Promise<ArtistProfileModel[]> {
    const structured = data.map((item) => CreateData(ArtistProfileModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ArtistProfile records
   */
  async purgeAllArtistProfile(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ArtistProfile records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listArtistProfile(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ArtistProfileModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get artist_profile by Id index
   * This function gets data by index.
   */
  async getArtistProfileById(
    id: string,
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_profile by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistProfileById(
    id: string,
    data: ArtistProfileModel
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexId(
      id
    );

    const values = ArtistProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_profile by Id index
   */
  async deleteArtistProfileById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_profile by UserId index
   * This function gets data by index.
   */
  async getArtistProfileByUserId(
    user_id: string,
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_profile by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistProfileByUserId(
    user_id: string,
    data: ArtistProfileModel
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ArtistProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_profile by UserId index
   */
  async deleteArtistProfileByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_profile by DataCreator index
   * This function gets data by index.
   */
  async getArtistProfileByDataCreator(
    data_creator: string,
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_profile by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistProfileByDataCreator(
    data_creator: string,
    data: ArtistProfileModel
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ArtistProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_profile by DataCreator index
   */
  async deleteArtistProfileByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get artist_profile by DataUpdater index
   * This function gets data by index.
   */
  async getArtistProfileByDataUpdater(
    data_updater: string,
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) artist_profile by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setArtistProfileByDataUpdater(
    data_updater: string,
    data: ArtistProfileModel
  ): Promise<ArtistProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ArtistProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete artist_profile by DataUpdater index
   */
  async deleteArtistProfileByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ArtistProfileModel data array
   */
  private resultToData(values: Data[]): ArtistProfileModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ArtistProfileModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ArtistProfileModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ArtistProfileModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ArtistProfileModel => item !== null);
  }
}

/**
 * Convert ArtistProfileModel data to Value array
 */
function ArtistProfileModelToValues(data: ArtistProfileModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'banner_image_url', type: DataType.string, defaultValue: null },
    { key: 'bio', type: DataType.string, defaultValue: null },
    { key: 'art_style_tags', type: DataType.array, defaultValue: null },
    { key: 'portfolio_image_urls', type: DataType.array, defaultValue: null },
    { key: 'commission_guidelines', type: DataType.string, defaultValue: null },
    { key: 'completed_work_count', type: DataType.number, defaultValue: 0 },
    { key: 'likes_count', type: DataType.number, defaultValue: 0 },
    { key: 'price_range_min', type: DataType.number, defaultValue: 0 },
    { key: 'price_range_max', type: DataType.number, defaultValue: 0 },
    { key: 'social_links', type: DataType.object, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ArtistProfileModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ArtistProfileModel data
 */
function ArtistProfileModelFromValues(values: Value[]): ArtistProfileModel {
  const data: Partial<ArtistProfileModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'banner_image_url':
        data.banner_image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'bio':
        data.bio = ParseValue(value, DataType.string) as string | null;
        break;
      case 'art_style_tags':
        data.art_style_tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'portfolio_image_urls':
        data.portfolio_image_urls = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'commission_guidelines':
        data.commission_guidelines = ParseValue(value, DataType.string) as string | null;
        break;
      case 'completed_work_count':
        data.completed_work_count = ParseValue(value, DataType.number) as number;
        break;
      case 'likes_count':
        data.likes_count = ParseValue(value, DataType.number) as number;
        break;
      case 'price_range_min':
        data.price_range_min = ParseValue(value, DataType.number) as number;
        break;
      case 'price_range_max':
        data.price_range_max = ParseValue(value, DataType.number) as number;
        break;
      case 'social_links':
        data.social_links = ParseValue(value, DataType.object) as ArtistProfileSocialLinksModel | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ArtistProfileModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ArtistProfileORM;