// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: payment_transaction.
// - Entity ID: 102019abe83be8a7213b3fd859ca0009c19.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PaymentTransactionStatus
 */
export enum PaymentTransactionStatus {
  Unspecified = 0,
  Pending = 1,
  Succeeded = 2,
  Failed = 3,
}



/**
 * Interface for PaymentTransactionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PaymentTransactionModel {
  id: string;
  commission_offer_id: string;
  stripe_session_id: string;
  status: PaymentTransactionStatus;
  amount: number;
  platform_fee_amount: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for PaymentTransaction entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PaymentTransactionORM {
  private static instance: PaymentTransactionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be8a7213b3fd859ca0009c19';
    this.entityName = 'payment_transaction';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of PaymentTransactionORM
   */
  public static getInstance(): PaymentTransactionORM {
    if (!PaymentTransactionORM.instance) {
      PaymentTransactionORM.instance = new PaymentTransactionORM();
    }
    
    return PaymentTransactionORM.instance;
  }

  /**
   * Get all PaymentTransaction records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPaymentTransaction(): Promise<PaymentTransactionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PaymentTransaction record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPaymentTransaction(data: PaymentTransactionModel[]): Promise<PaymentTransactionModel[]> {
    const structured = data.map((item) => CreateData(PaymentTransactionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PaymentTransaction records
   */
  async purgeAllPaymentTransaction(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PaymentTransaction records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPaymentTransaction(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PaymentTransactionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get payment_transaction by Id index
   * This function gets data by index.
   */
  async getPaymentTransactionById(
    id: string,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionById(
    id: string,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexId(
      id
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by Id index
   */
  async deletePaymentTransactionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payment_transaction by CommissionOfferId index
   * This function gets data by index.
   */
  async getPaymentTransactionByCommissionOfferId(
    commission_offer_id: string,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexCommissionOfferId(
      commission_offer_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by CommissionOfferId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionByCommissionOfferId(
    commission_offer_id: string,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexCommissionOfferId(
      commission_offer_id
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by CommissionOfferId index
   */
  async deletePaymentTransactionByCommissionOfferId(
    commission_offer_id: string
  ): Promise<void> {
    const index = createIndexCommissionOfferId(
      commission_offer_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payment_transaction by StripeSessionId index
   * This function gets data by index.
   */
  async getPaymentTransactionByStripeSessionId(
    stripe_session_id: string,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexStripeSessionId(
      stripe_session_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by StripeSessionId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionByStripeSessionId(
    stripe_session_id: string,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexStripeSessionId(
      stripe_session_id
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by StripeSessionId index
   */
  async deletePaymentTransactionByStripeSessionId(
    stripe_session_id: string
  ): Promise<void> {
    const index = createIndexStripeSessionId(
      stripe_session_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payment_transaction by Status index
   * This function gets data by index.
   */
  async getPaymentTransactionByStatus(
    status: PaymentTransactionStatus,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionByStatus(
    status: PaymentTransactionStatus,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by Status index
   */
  async deletePaymentTransactionByStatus(
    status: PaymentTransactionStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payment_transaction by DataCreator index
   * This function gets data by index.
   */
  async getPaymentTransactionByDataCreator(
    data_creator: string,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionByDataCreator(
    data_creator: string,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by DataCreator index
   */
  async deletePaymentTransactionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payment_transaction by DataUpdater index
   * This function gets data by index.
   */
  async getPaymentTransactionByDataUpdater(
    data_updater: string,
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payment_transaction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPaymentTransactionByDataUpdater(
    data_updater: string,
    data: PaymentTransactionModel
  ): Promise<PaymentTransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PaymentTransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payment_transaction by DataUpdater index
   */
  async deletePaymentTransactionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PaymentTransactionModel data array
   */
  private resultToData(values: Data[]): PaymentTransactionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PaymentTransactionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PaymentTransactionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PaymentTransactionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PaymentTransactionModel => item !== null);
  }
}

/**
 * Convert PaymentTransactionModel data to Value array
 */
function PaymentTransactionModelToValues(data: PaymentTransactionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'commission_offer_id', type: DataType.string, defaultValue: '' },
    { key: 'stripe_session_id', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'platform_fee_amount', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PaymentTransactionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PaymentTransactionModel data
 */
function PaymentTransactionModelFromValues(values: Value[]): PaymentTransactionModel {
  const data: Partial<PaymentTransactionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'commission_offer_id':
        data.commission_offer_id = ParseValue(value, DataType.string) as string;
        break;
      case 'stripe_session_id':
        data.stripe_session_id = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as PaymentTransactionStatus;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'platform_fee_amount':
        data.platform_fee_amount = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as PaymentTransactionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CommissionOfferId fields
 */
function createIndexCommissionOfferId(
  commission_offer_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, commission_offer_id, 'commission_offer_id'),
  ];

  return {
    fields: ['commission_offer_id'],
    values
  };
}
/**
 * Create index for StripeSessionId fields
 */
function createIndexStripeSessionId(
  stripe_session_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, stripe_session_id, 'stripe_session_id'),
  ];

  return {
    fields: ['stripe_session_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: PaymentTransactionStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default PaymentTransactionORM;