// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: commission_request.
// - Entity ID: 102019abe83be8a76dcac834b89d36cf9a1.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for CommissionRequestStatus
 */
export enum CommissionRequestStatus {
  Unspecified = 0,
  Open = 1,
  InProgress = 2,
  Closed = 3,
}



/**
 * Interface for CommissionRequestModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CommissionRequestModel {
  id: string;
  poster_id: string;
  title: string;
  description: string;
  sample_image_urls?: string[] | null;
  budget_min: number;
  budget_max: number;
  tags?: string[] | null;
  status: CommissionRequestStatus;
  interested_artist_ids?: string[] | null;
  poster?: {
    id: string;
    display_name: string;
    avatar_url?: string | null;
    username: string;
  };
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for CommissionRequest entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CommissionRequestORM {
  private static instance: CommissionRequestORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be8a76dcac834b89d36cf9a1';
    this.entityName = 'commission_request';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of CommissionRequestORM
   */
  public static getInstance(): CommissionRequestORM {
    if (!CommissionRequestORM.instance) {
      CommissionRequestORM.instance = new CommissionRequestORM();
    }
    
    return CommissionRequestORM.instance;
  }

  /**
   * Get all CommissionRequest records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCommissionRequest(): Promise<CommissionRequestModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new CommissionRequest record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCommissionRequest(data: CommissionRequestModel[]): Promise<CommissionRequestModel[]> {
    const structured = data.map((item) => CreateData(CommissionRequestModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all CommissionRequest records
   */
  async purgeAllCommissionRequest(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List CommissionRequest records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCommissionRequest(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CommissionRequestModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get commission_request by Id index
   * This function gets data by index.
   */
  async getCommissionRequestById(
    id: string,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestById(
    id: string,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexId(
      id
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by Id index
   */
  async deleteCommissionRequestById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_request by PosterId index
   * This function gets data by index.
   */
  async getCommissionRequestByPosterId(
    poster_id: string,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexPosterId(
      poster_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by PosterId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestByPosterId(
    poster_id: string,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexPosterId(
      poster_id
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by PosterId index
   */
  async deleteCommissionRequestByPosterId(
    poster_id: string
  ): Promise<void> {
    const index = createIndexPosterId(
      poster_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_request by Status index
   * This function gets data by index.
   */
  async getCommissionRequestByStatus(
    status: CommissionRequestStatus,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestByStatus(
    status: CommissionRequestStatus,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by Status index
   */
  async deleteCommissionRequestByStatus(
    status: CommissionRequestStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_request by CreateTime index
   * This function gets data by index.
   */
  async getCommissionRequestByCreateTime(
    create_time: string,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestByCreateTime(
    create_time: string,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by CreateTime index
   */
  async deleteCommissionRequestByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_request by DataCreator index
   * This function gets data by index.
   */
  async getCommissionRequestByDataCreator(
    data_creator: string,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestByDataCreator(
    data_creator: string,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by DataCreator index
   */
  async deleteCommissionRequestByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_request by DataUpdater index
   * This function gets data by index.
   */
  async getCommissionRequestByDataUpdater(
    data_updater: string,
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_request by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionRequestByDataUpdater(
    data_updater: string,
    data: CommissionRequestModel
  ): Promise<CommissionRequestModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CommissionRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_request by DataUpdater index
   */
  async deleteCommissionRequestByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CommissionRequestModel data array
   */
  private resultToData(values: Data[]): CommissionRequestModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CommissionRequestModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CommissionRequestModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CommissionRequestModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CommissionRequestModel => item !== null);
  }
}

/**
 * Convert CommissionRequestModel data to Value array
 */
function CommissionRequestModelToValues(data: CommissionRequestModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'poster_id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: '' },
    { key: 'sample_image_urls', type: DataType.array, defaultValue: null },
    { key: 'budget_min', type: DataType.number, defaultValue: 0 },
    { key: 'budget_max', type: DataType.number, defaultValue: 0 },
    { key: 'tags', type: DataType.array, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'interested_artist_ids', type: DataType.array, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CommissionRequestModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CommissionRequestModel data
 */
function CommissionRequestModelFromValues(values: Value[]): CommissionRequestModel {
  const data: Partial<CommissionRequestModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'poster_id':
        data.poster_id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string;
        break;
      case 'sample_image_urls':
        data.sample_image_urls = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'budget_min':
        data.budget_min = ParseValue(value, DataType.number) as number;
        break;
      case 'budget_max':
        data.budget_max = ParseValue(value, DataType.number) as number;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as CommissionRequestStatus;
        break;
      case 'interested_artist_ids':
        data.interested_artist_ids = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as CommissionRequestModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for PosterId fields
 */
function createIndexPosterId(
  poster_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, poster_id, 'poster_id'),
  ];

  return {
    fields: ['poster_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: CommissionRequestStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default CommissionRequestORM;
