// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: timeline_post.
// - Entity ID: 102019abe83be897c288b942a166f052be3.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TimelinePostModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TimelinePostModel {
  id: string;
  author_id: string;
  body: string;
  image_urls?: string[] | null;
  tags?: string[] | null;
  likes_count: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for TimelinePost entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TimelinePostORM {
  private static instance: TimelinePostORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be897c288b942a166f052be3';
    this.entityName = 'timeline_post';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of TimelinePostORM
   */
  public static getInstance(): TimelinePostORM {
    if (!TimelinePostORM.instance) {
      TimelinePostORM.instance = new TimelinePostORM();
    }
    
    return TimelinePostORM.instance;
  }

  /**
   * Get all TimelinePost records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTimelinePost(): Promise<TimelinePostModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TimelinePost record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTimelinePost(data: TimelinePostModel[]): Promise<TimelinePostModel[]> {
    const structured = data.map((item) => CreateData(TimelinePostModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TimelinePost records
   */
  async purgeAllTimelinePost(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TimelinePost records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTimelinePost(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TimelinePostModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get timeline_post by Id index
   * This function gets data by index.
   */
  async getTimelinePostById(
    id: string,
  ): Promise<TimelinePostModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) timeline_post by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimelinePostById(
    id: string,
    data: TimelinePostModel
  ): Promise<TimelinePostModel[]> {
    const index = createIndexId(
      id
    );

    const values = TimelinePostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete timeline_post by Id index
   */
  async deleteTimelinePostById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get timeline_post by AuthorId index
   * This function gets data by index.
   */
  async getTimelinePostByAuthorId(
    author_id: string,
  ): Promise<TimelinePostModel[]> {
    const index = createIndexAuthorId(
      author_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) timeline_post by AuthorId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimelinePostByAuthorId(
    author_id: string,
    data: TimelinePostModel
  ): Promise<TimelinePostModel[]> {
    const index = createIndexAuthorId(
      author_id
    );

    const values = TimelinePostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete timeline_post by AuthorId index
   */
  async deleteTimelinePostByAuthorId(
    author_id: string
  ): Promise<void> {
    const index = createIndexAuthorId(
      author_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get timeline_post by CreateTime index
   * This function gets data by index.
   */
  async getTimelinePostByCreateTime(
    create_time: string,
  ): Promise<TimelinePostModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) timeline_post by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimelinePostByCreateTime(
    create_time: string,
    data: TimelinePostModel
  ): Promise<TimelinePostModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = TimelinePostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete timeline_post by CreateTime index
   */
  async deleteTimelinePostByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get timeline_post by DataCreator index
   * This function gets data by index.
   */
  async getTimelinePostByDataCreator(
    data_creator: string,
  ): Promise<TimelinePostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) timeline_post by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimelinePostByDataCreator(
    data_creator: string,
    data: TimelinePostModel
  ): Promise<TimelinePostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TimelinePostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete timeline_post by DataCreator index
   */
  async deleteTimelinePostByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get timeline_post by DataUpdater index
   * This function gets data by index.
   */
  async getTimelinePostByDataUpdater(
    data_updater: string,
  ): Promise<TimelinePostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) timeline_post by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimelinePostByDataUpdater(
    data_updater: string,
    data: TimelinePostModel
  ): Promise<TimelinePostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TimelinePostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete timeline_post by DataUpdater index
   */
  async deleteTimelinePostByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TimelinePostModel data array
   */
  private resultToData(values: Data[]): TimelinePostModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TimelinePostModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TimelinePostModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TimelinePostModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TimelinePostModel => item !== null);
  }
}

/**
 * Convert TimelinePostModel data to Value array
 */
function TimelinePostModelToValues(data: TimelinePostModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'author_id', type: DataType.string, defaultValue: '' },
    { key: 'body', type: DataType.string, defaultValue: '' },
    { key: 'image_urls', type: DataType.array, defaultValue: null },
    { key: 'tags', type: DataType.array, defaultValue: null },
    { key: 'likes_count', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TimelinePostModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TimelinePostModel data
 */
function TimelinePostModelFromValues(values: Value[]): TimelinePostModel {
  const data: Partial<TimelinePostModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'author_id':
        data.author_id = ParseValue(value, DataType.string) as string;
        break;
      case 'body':
        data.body = ParseValue(value, DataType.string) as string;
        break;
      case 'image_urls':
        data.image_urls = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'likes_count':
        data.likes_count = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as TimelinePostModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for AuthorId fields
 */
function createIndexAuthorId(
  author_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, author_id, 'author_id'),
  ];

  return {
    fields: ['author_id'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TimelinePostORM;