// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: commission_offer.
// - Entity ID: 102019abe83be8a7081aa483561cb186857.
// - Entity Version: 102019ac164d6447c6285964527898cdb09.
// - Task ID: 692744b9b0964306551800aa.
// - Task Root ID: 6926863bc42fb3866ca5f41d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for CommissionOfferStatus
 */
export enum CommissionOfferStatus {
  Unspecified = 0,
  Pending = 1,
  Accepted = 2,
  Rejected = 3,
  Completed = 4,
}



/**
 * Interface for CommissionOfferModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CommissionOfferModel {
  id: string;
  artist_id: string;
  buyer_id: string;
  commission_request_id?: string | null;
  description: string;
  price: number;
  deposit_amount?: number | null;
  status: CommissionOfferStatus;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for CommissionOffer entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CommissionOfferORM {
  private static instance: CommissionOfferORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019abe83be8a7081aa483561cb186857';
    this.entityName = 'commission_offer';
    this.entityVersion = '102019ac164d6447c6285964527898cdb09';
    this.taskId = '692744b9b0964306551800aa';
    this.taskRootId = '6926863bc42fb3866ca5f41d';
  }

  /**
   * Get singleton instance of CommissionOfferORM
   */
  public static getInstance(): CommissionOfferORM {
    if (!CommissionOfferORM.instance) {
      CommissionOfferORM.instance = new CommissionOfferORM();
    }
    
    return CommissionOfferORM.instance;
  }

  /**
   * Get all CommissionOffer records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCommissionOffer(): Promise<CommissionOfferModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new CommissionOffer record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCommissionOffer(data: CommissionOfferModel[]): Promise<CommissionOfferModel[]> {
    const structured = data.map((item) => CreateData(CommissionOfferModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all CommissionOffer records
   */
  async purgeAllCommissionOffer(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List CommissionOffer records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCommissionOffer(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CommissionOfferModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get commission_offer by Id index
   * This function gets data by index.
   */
  async getCommissionOfferById(
    id: string,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferById(
    id: string,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexId(
      id
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by Id index
   */
  async deleteCommissionOfferById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by ArtistId index
   * This function gets data by index.
   */
  async getCommissionOfferByArtistId(
    artist_id: string,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexArtistId(
      artist_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by ArtistId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByArtistId(
    artist_id: string,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexArtistId(
      artist_id
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by ArtistId index
   */
  async deleteCommissionOfferByArtistId(
    artist_id: string
  ): Promise<void> {
    const index = createIndexArtistId(
      artist_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by BuyerId index
   * This function gets data by index.
   */
  async getCommissionOfferByBuyerId(
    buyer_id: string,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexBuyerId(
      buyer_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by BuyerId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByBuyerId(
    buyer_id: string,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexBuyerId(
      buyer_id
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by BuyerId index
   */
  async deleteCommissionOfferByBuyerId(
    buyer_id: string
  ): Promise<void> {
    const index = createIndexBuyerId(
      buyer_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by Status index
   * This function gets data by index.
   */
  async getCommissionOfferByStatus(
    status: CommissionOfferStatus,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByStatus(
    status: CommissionOfferStatus,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by Status index
   */
  async deleteCommissionOfferByStatus(
    status: CommissionOfferStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by ArtistIdStatus index
   * This function gets data by index.
   */
  async getCommissionOfferByArtistIdStatus(
    artist_id: string,
    status: CommissionOfferStatus,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexArtistIdStatus(
      artist_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by ArtistIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByArtistIdStatus(
    artist_id: string,
    status: CommissionOfferStatus,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexArtistIdStatus(
      artist_id,
      status
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by ArtistIdStatus index
   */
  async deleteCommissionOfferByArtistIdStatus(
    artist_id: string,
    status: CommissionOfferStatus
  ): Promise<void> {
    const index = createIndexArtistIdStatus(
      artist_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by BuyerIdStatus index
   * This function gets data by index.
   */
  async getCommissionOfferByBuyerIdStatus(
    buyer_id: string,
    status: CommissionOfferStatus,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexBuyerIdStatus(
      buyer_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by BuyerIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByBuyerIdStatus(
    buyer_id: string,
    status: CommissionOfferStatus,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexBuyerIdStatus(
      buyer_id,
      status
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by BuyerIdStatus index
   */
  async deleteCommissionOfferByBuyerIdStatus(
    buyer_id: string,
    status: CommissionOfferStatus
  ): Promise<void> {
    const index = createIndexBuyerIdStatus(
      buyer_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by DataCreator index
   * This function gets data by index.
   */
  async getCommissionOfferByDataCreator(
    data_creator: string,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByDataCreator(
    data_creator: string,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by DataCreator index
   */
  async deleteCommissionOfferByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get commission_offer by DataUpdater index
   * This function gets data by index.
   */
  async getCommissionOfferByDataUpdater(
    data_updater: string,
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) commission_offer by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCommissionOfferByDataUpdater(
    data_updater: string,
    data: CommissionOfferModel
  ): Promise<CommissionOfferModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CommissionOfferModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete commission_offer by DataUpdater index
   */
  async deleteCommissionOfferByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CommissionOfferModel data array
   */
  private resultToData(values: Data[]): CommissionOfferModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CommissionOfferModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CommissionOfferModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CommissionOfferModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CommissionOfferModel => item !== null);
  }
}

/**
 * Convert CommissionOfferModel data to Value array
 */
function CommissionOfferModelToValues(data: CommissionOfferModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'artist_id', type: DataType.string, defaultValue: '' },
    { key: 'buyer_id', type: DataType.string, defaultValue: '' },
    { key: 'commission_request_id', type: DataType.string, defaultValue: null },
    { key: 'description', type: DataType.string, defaultValue: '' },
    { key: 'price', type: DataType.number, defaultValue: 0 },
    { key: 'deposit_amount', type: DataType.number, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CommissionOfferModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CommissionOfferModel data
 */
function CommissionOfferModelFromValues(values: Value[]): CommissionOfferModel {
  const data: Partial<CommissionOfferModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'artist_id':
        data.artist_id = ParseValue(value, DataType.string) as string;
        break;
      case 'buyer_id':
        data.buyer_id = ParseValue(value, DataType.string) as string;
        break;
      case 'commission_request_id':
        data.commission_request_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string;
        break;
      case 'price':
        data.price = ParseValue(value, DataType.number) as number;
        break;
      case 'deposit_amount':
        data.deposit_amount = ParseValue(value, DataType.number) as number | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as CommissionOfferStatus;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as CommissionOfferModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ArtistId fields
 */
function createIndexArtistId(
  artist_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, artist_id, 'artist_id'),
  ];

  return {
    fields: ['artist_id'],
    values
  };
}
/**
 * Create index for BuyerId fields
 */
function createIndexBuyerId(
  buyer_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, buyer_id, 'buyer_id'),
  ];

  return {
    fields: ['buyer_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: CommissionOfferStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for ArtistIdStatus fields
 */
function createIndexArtistIdStatus(
  artist_id: string,
  status: CommissionOfferStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, artist_id, 'artist_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['artist_id', 'status'],
    values
  };
}
/**
 * Create index for BuyerIdStatus fields
 */
function createIndexBuyerIdStatus(
  buyer_id: string,
  status: CommissionOfferStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, buyer_id, 'buyer_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['buyer_id', 'status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default CommissionOfferORM;